This is a Jupyter notebook to store all the things I have learned about Linear Algebra by using Tensorflow.
We are going to use `tf.linalg` from Tensorflow [linalg](https://www.tensorflow.org/api_docs/python/tf/linalg/) function to perform linear algebraic operations.

In [2]:
# Let us start by importing the base module tensorflow and make sure that we are using the latest version.
import tensorflow as tf
print(tf.__version__)

2.4.0-dev20201003



<a id="basics"></a>

## Basics

Tensorflow operates on `Tensors`. `Tensors` are characterized by their rank. Following table shows different types of tensors and their corresponding rank.

|Tensors|  Rank    |
|:----:|:----:|
|Scalars|Rank 0 Tensor|
|Vectors (1D array)| Rank 1 Tensor|
|Matrices (2D array)| Rank 2 Tensor|
|3D array| Rank 3 Tensor|


While using Tensorflow matrices operations using linalg if an array has a shape of (x, y, z), it can be thought of as 3 matrices each of shape (y, z). When we call a matrix function on this array, the matrix function is applied to all 3 matrices of shape (y, z). This is also true for higher dimensional arrays.

In [3]:
import numpy as np

In [4]:
# A scalar tensor
rank_0_tensor = tf.constant(1)
print('Scalar Tensor : ', rank_0_tensor,'\n')

# To access the value of the tensor you can use the following way
# print(rank_0_tensor.numpy())

# A vector tensor
rank_1_tensor = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
print('Vector Tensor : ', rank_1_tensor,'\n')

# A matrix
rank_2_tensor = tf.constant([[1, 2],
[3, 4],
[5, 6]])
print('Matrix as a Tensor : \n', rank_2_tensor, '\n')

# A 3D array
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print('Vector as a Tensor : \n', rank_3_tensor, '\n')




Scalar Tensor :  tf.Tensor(1, shape=(), dtype=int32) 

Vector Tensor :  tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32) 

Matrix as a Tensor : 
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

Vector as a Tensor : 
 tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32) 



In [5]:
# You can create a tensorflow Variable too just like creating a constant as shown above.

tf_variable = tf.Variable(rank_0_tensor, name="Rank0Tensor")

In [6]:
# It is also possible to generate sequence of numbers using Tensorflow.print. Impotant to note here is that the element `limit` is not counted here also as per Python rules. Check python documentation for more details.

seq_of_nos = tf.range(start=1, limit=9, delta=1, name="range")
print(seq_of_nos, '\n')
print('Tensor Value : ', seq_of_nos.numpy(), '\n' )

# You can also use linspace as shown below.
# Linspace creates as `stop - start / num - 1` .
seq_using_lin = tf.linspace(start=1.0, stop=9, num=5, name="Linspace")
print('Linspace usage : ', seq_using_lin)

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32) 

Tensor Value :  [1 2 3 4 5 6 7 8] 

Linspace usage :  tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


In [9]:
# We can also slice the vectors.

slic_vec = tf.range(start=1, limit=9)
print(slic_vec)
slic_vec[1:4].numpy()

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)


array([2, 3, 4], dtype=int32)

In [20]:
# To create matrices using tensorflow is also easy. 
# Here we try to create a 4X2 which is a four by two matrix.

matrices = tf.constant(tf.range(20, dtype=tf.float32), shape=(4,5))
print(matrices)

tf.Tensor(
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]], shape=(4, 5), dtype=float32)


In [22]:
# We can also slice the matrix as desired.
# To decode this you can read it as select index 2 to index 4 elements from row index 1 to row index 3. TO better understand this as indexes start with `0` in python it here means that select element 3 and 4 from rows 1 and 2 in plain terms.

matrices1 = matrices[1:3, 2:4]
print(matrices1)

tf.Tensor(
[[ 7.  8.]
 [12. 13.]], shape=(2, 2), dtype=float32)
