This is a Jupyter notebook to store all the things I have learned about Linear Algebra by using Tensorflow.
We are going to use `tf.linalg` from Tensorflow [linalg](https://www.tensorflow.org/api_docs/python/tf/linalg/) function to perform linear algebraic operations.

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ashwin-phadke/implementations-and-guides/blob/master/Deep%20Learning%20with%20TensorFlow/Linear_Algebra_using_TensorFlow.ipynb)

In [1]:
# Let us start by importing the base module tensorflow and make sure that we are using the latest version.
import tensorflow as tf
print(tf.__version__)

2.4.0-dev20201003



<a id="basics"></a>

## Basics

Tensorflow operates on `Tensors`. `Tensors` are characterized by their rank. Following table shows different types of tensors and their corresponding rank.

|Tensors|  Rank    |
|:----:|:----:|
|Scalars|Rank 0 Tensor|
|Vectors (1D array)| Rank 1 Tensor|
|Matrices (2D array)| Rank 2 Tensor|
|3D array| Rank 3 Tensor|


While using Tensorflow matrices operations using linalg if an array has a shape of (x, y, z), it can be thought of as 3 matrices each of shape (y, z). When we call a matrix function on this array, the matrix function is applied to all 3 matrices of shape (y, z). This is also true for higher dimensional arrays.

In [5]:
import numpy as np

In [27]:
# A scalar tensor
rank_0_tensor = tf.constant(1)
print('Scalar Tensor : ', rank_0_tensor,'\n')

# To access the value of the tensor you can use the following way
# print(rank_0_tensor.numpy())

# A vector tensor
rank_1_tensor = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
print('Vector Tensor : ', rank_1_tensor,'\n')

# A matrix
rank_2_tensor = tf.constant([[1, 2],
[3, 4],
[5, 6]])
print('Matrix as a Tensor : \n', rank_2_tensor, '\n')

# A 3D array
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print('Vector as a Tensor : \n', rank_3_tensor, '\n')




Scalar Tensor :  tf.Tensor(1, shape=(), dtype=int32) 

Vector Tensor :  tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32) 

Matrix as a Tensor : 
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

Vector as a Tensor : 
 tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32) 



In [28]:
# You can create a tensorflow Variable too just like creating a constant as shown above.

tf_variable = tf.Variable(rank_0_tensor, name="Rank0Tensor")

In [29]:
# It is also possible to generate sequence of numbers using Tensorflow.print. Impotant to note here is that the element `limit` is not counted here also as per Python rules. Check python documentation for more details.

seq_of_nos = tf.range(start=1, limit=9, delta=1, name="range")
print(seq_of_nos, '\n')
print('Tensor Value : ', seq_of_nos.numpy(), '\n' )

# You can also use linspace as shown below.
# Linspace creates as `stop - start / num - 1` .
seq_using_lin = tf.linspace(start=1.0, stop=9, num=5, name="Linspace")
print('Linspace usage : ', seq_using_lin)

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32) 

Tensor Value :  [1 2 3 4 5 6 7 8] 

Linspace usage :  tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float32)


In [30]:
# We can also slice the vectors.

slic_vec = tf.range(start=1, limit=9)
print(slic_vec)
slic_vec[1:4].numpy()

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)


array([2, 3, 4], dtype=int32)

In [31]:
# To create matrices using tensorflow is also easy. 
# Here we try to create a 4X2 which is a four by two matrix.

matrices = tf.constant(tf.range(20, dtype=tf.float32), shape=(4,5))
print(matrices)

tf.Tensor(
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]], shape=(4, 5), dtype=float32)


In [32]:
# We can also slice the matrix as desired.
# To decode this you can read it as select index 2 to index 4 elements from row index 1 to row index 3. TO better understand this as indexes start with `0` in python it here means that select element 3 and 4 from rows 1 and 2 in plain terms.

matrices1 = matrices[1:3, 2:4]
print(matrices1)

tf.Tensor(
[[ 7.  8.]
 [12. 13.]], shape=(2, 2), dtype=float32)


In [33]:
# If we create a matrix using above method we will not be able to change the values inside the matrix as tensors in tensorflow cannot be modified. Instead, we create a tensor variable. To change the variables at any time first create a matrix using tensor variable and then assign new values inside the matrix by using tensor align function.

# Matrix creation
variable_mat = tf.Variable(tf.constant(tf.range(12, dtype = tf.float32), shape = (3,4)))
print(variable_mat)


# We change the values from 1st and 2nd row from 3rd and 4th columns. tf.ones returns elements as 1 with the provided shape.
variable_mat[:2,2:4].assign(-1*tf.ones(shape = (2,2)))
variable_mat

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)>


<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1., -1., -1.],
       [ 4.,  5., -1., -1.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

In [34]:
# To create a transpose of a matrix simply use tf.transpose function and pass the desired matrix tensor.
# tf.transpose(), tf.linalg.adjoint() and tf.linalg.matix_transpose() are some other functions that give similar results.
tf.transpose(variable_mat)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [-1., -1., 10.],
       [-1., -1., 11.]], dtype=float32)>

In [35]:
#To calculate the determinant of a square matrix 

determinant_of_matrix = tf.linalg.det(
    input = tf.Variable(tf.constant(tf.range(16, dtype = tf.float32), shape = (4,4))), name=None
)
print(determinant_of_matrix.numpy())

0.0


In [36]:
# Construct one identity matrix.
print(tf.eye(2))


# Construct a batch of 3 identity matrices, each 2 x 2.
# batch_identity[i, :, :] is a 2 x 2 identity matrix, i = 0, 1, 2.
batch_identity = tf.eye(2, batch_shape=[3])
print(batch_identity)

# Construct one 2 x 3 "identity" matrix
print(tf.eye(2, num_columns=3))



tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]], shape=(2, 3), dtype=float32)


In [37]:
# addition of two matrices 

a = tf.constant([1,2,3])

b = tf.constant([1,2,3])

c = tf.add(A1, B1)
print("Matrix A {0} + Matrix B {1} = {2}".format(a, b, c))

Matrix A [1 2 3] + Matrix B [1 2 3] = [2 4 6]


In [38]:
# Create a diagonal matrix

diag_matrix = tf.linalg.diag(diagonal=[1,2,3], num_rows=3, num_cols=3)
print(diag_matrix)

# Or we can use

diag_matrix = tf.linalg.tensor_diag(tf.constant([1,2,3,4,5]))
print(diag_matrix)

tf.Tensor(
[[1 0 0]
 [0 2 0]
 [0 0 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]], shape=(5, 5), dtype=int32)


In [39]:
# Multiply matrix A by a vector B.

# 2-D tensor
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
#print(a)

# 1-D tensor
b = tf.constant([7, 9, 11], shape=[3])

# a * b
c = tf.linalg.matvec(a, b)

print("Matrix A: {0} multipled by Vector B : {1} equals too {2}".format(a.numpy(), b, c))




Matrix A: [[1 2 3]
 [4 5 6]] multipled by Vector B : [ 7  9 11] equals too [ 58 139]


In [6]:

# 3-D tensor `a`
a = tf.constant(np.arange(1, 13, dtype=np.int32),
                shape=[2, 2, 3])

# 2-D tensor `b`
b = tf.constant(np.arange(13, 19, dtype=np.int32),
                shape=[2, 3])

# `a` * `b`
c = tf.linalg.matvec(a, b)

print("Matrix A: {0} multipled by Vector B : {1} equals too {2}".format(a.numpy(), b, *c))


Matrix A: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] multipled by Vector B : [[13 14 15]
 [16 17 18]] equals too [ 86 212]


References used :

1. Tensorflow documentation : [linalg](https://www.tensorflow.org/api_docs/python/tf/linalg)
2. Linear algebra blog : [Link](https://biswajitsahoo1111.github.io/post/doing-linear-algebra-using-tensorflow-2/)
3. Tensorflow blog : [Link](https://learningtensorflow.com/learning-tensorflow-linear-algebra-lesson-10-linear-equations/)