This is a Jupyter notebook to store all the things I have learned about Linear Algebra by using Tensorflow.
We are going to use `tf.linalg` from Tensorflow [linalg](https://www.tensorflow.org/api_docs/python/tf/linalg/) function to perform linear algebraic operations.

In [4]:
# Let us start by importing the base module tensorflow and make sure that we are using the latest version.
import tensorflow as tf
print(tf.__version__)

2.4.0-dev20201003



<a id="basics"></a>

## Basics

Tensorflow operates on `Tensors`. `Tensors` are characterized by their rank. Following table shows different types of tensors and their corresponding rank.

|Tensors|  Rank    |
|:----:|:----:|
|Scalars|Rank 0 Tensor|
|Vectors (1D array)| Rank 1 Tensor|
|Matrices (2D array)| Rank 2 Tensor|
|3D array| Rank 3 Tensor|


While using Tensorflow matrices operations using linalg if an array has a shape of (x, y, z), it can be thought of as 3 matrices each of shape (y, z). When we call a matrix function on this array, the matrix function is applied to all 3 matrices of shape (y, z). This is also true for higher dimensional arrays.

In [6]:
import numpy as np

In [17]:
# A scalar tensor
rank_0_tensor = tf.constant(1)
print('Scalar Tensor : ', rank_0_tensor,'\n')

# To access the value of the tensor you can use the following way
# print(rank_0_tensor.numpy())

# A vector tensor
rank_1_tensor = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
print('Vector Tensor : ', rank_1_tensor,'\n')

# A matrix
rank_2_tensor = tf.constant([[1, 2],
[3, 4],
[5, 6]])
print('Matrix as a Tensor : \n', rank_2_tensor, '\n')

# A 3D array
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
print('Vector as a Tensor : \n', rank_3_tensor, '\n')




Scalar Tensor :  tf.Tensor(1, shape=(), dtype=int32) 

1
Vector Tensor :  tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32) 

Matrix as a Tensor : 
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

Vector as a Tensor : 
 tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32) 

